// Generated by Selenium IDE


import ActWebSite.ActWebSite;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.Map;
import java.util.concurrent.TimeUnit;

public class LoginPeterTest {
    JavascriptExecutor js;
    //    private String baseURL = "http://192.168.1.17:8080/";
    private String baseURL = "http://127.1.1.17:8080/";
    private WebDriver driver;
    private Map<String, Object> vars;

//    @BeforeClass
//    private void BeforeClass(){
//
//    }

    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "D:\\Documents Peter\\IdeaProjects\\12.09.2020_reg\\drivers\\geckodriver.exe");
        driver = new FirefoxDriver();
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        driver.manage().window().maximize();
        driver.get(baseURL);


    }

    @After
    public void tierDown() {
//        ActWebSite.ActWebSite.Exit(driver);
        driver.quit();
    }


//    @AfterClass
//    private void ArterClass(){
//        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//        driver.quit();
//
//    }

    @Test
    public void LoginPeter() {

        ActWebSite.Login("Peter", "123123", driver);
        WebElement webElement = driver.findElement(By.xpath("/html/body/div/div/h4[3]/a"));
        Assert.assertEquals(webElement.getText(), "Запись на курсы");

    }

    @Test
    public void Exit() {
        ActWebSite.Login("Peter", "123123", driver);
        ActWebSite.Exit(driver);

        WebElement webElement = driver.findElement(By.xpath("/html/body/div/div/h4[1]/a"));

        Assert.assertEquals("не удалось найти ссылку на Вход", webElement.getText(), "Войти");
    }

    @Test
    public void RegistLogin() {
        String loginUser = "user";
        String pass = "123123";
        ActWebSite.Regist(loginUser,
                pass,
                driver);
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        WebElement webElement = driver.findElement(By.xpath("/html/body/div/form/h2"));

        Assert.assertEquals("не удалось найти ссылку на Вход", webElement.getText(), "Вход в систему");
    }

    @Test
    public void RegistFio() {
        String loginUser = "user";
        String pass = "123123";

        String firstName = "userFirstName";
        String lastName = "userLastName";
        String middleName = "userMiddleName";
        String eMail = "e@mail.ru";
        String phone = "79211234562";

        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

        ActWebSite.Login(loginUser, pass, driver);
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        ActWebSite.setFio(
                firstName,
                lastName,
                middleName,
                eMail,
                phone,
                driver
        );
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        WebElement webElement = driver.findElement(By.xpath("/html/body/div/div/h4[3]/a"));
        Assert.assertEquals(webElement.getText(), "Запись на курсы");
    }


    @Test
    public void DellUser() {
        String loginUser = "Peter";
        String pass = "123123";
        ActWebSite.Login(loginUser, pass, driver);
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        ActWebSite.DellUser(loginUser, pass, driver);
    }

    @Test
    public void CheckInCourse() {

    }

}
